version: "3.8"

services:
  backend:
    depends_on:
      - db
    build: ./backend
    ports:
      - 3000:3000
    environment:
      DB_URL: mongodb://db/backend

    command: ./docker-entrypoint.sh

  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 3001:3001

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - backend:/data/db

volumes:
  backend:
